version: 2.1
workflows:
  publish: 
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - publish:
          requires: [build]
          filters:
            branches:
              only: master


jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          command: yarn install
      - run:
          name: Build
          command: |
            yarn build
  publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          command: yarn install
      - run:
          name: Deploy to GH Pages
          command: |
            yarn add --dev gh-pages
            git config --global user.email "ollitech@gmail.com"
            git config --global user.name "Eddie Webb"
            yarn deploy